# preprocess settings
preprocess:
    resampling: True
    resampling_type: over
    resampling_seed: 71

# training settings
train:
    fold_num: 5

# lightGBM parameters
lgbm_params:
    verbose: -1
    random_state: 71
    objective: binary
    metric: auc
    learning_rate: 0.05
    num_leaves: 25
    max_depth: -1
    subsample: 0.8
    colsample_bytree: 0.8
    bagging_freq: 1
    #    reg_alpha: 
    #    reg_lambda: 
    #    min_split_gain: 
    #    min_child_weight: 
    #    max_bin: 

# features
features: 
    - phase
    - e001_base_max
    - e001_base_min
    - e001_base_std
