# preprocess settings
preprocess:
    resampling: False
    resampling_type: under
    resampling_seed: 71

# training settings
train:
    fold_num: 5

# lightGBM parameters
lgbm_params:
    boosting: gbdt
    verbose: -1
    random_state: 71
    objective: binary
    metric: auc
    learning_rate: 0.05
    num_leaves: 80
    max_depth: -1
    subsample: 0.8
    bagging_freq: 1
    colsample_bytree: 0.8
    feature_fraction: 0.8
    min_data_in_leaf: 60
    lambda_l1: 0.1
    #    min_split_gain: 
    #    min_child_weight: 
    #    max_bin: 

# features
features: 
    #    - phase
    - e001_base_max
    - e001_base_min
    - e001_base_std
    - e002_hp_dn_basic_max
    - e002_hp_dn_basic_min
    - e002_hp_dn_basic_std
      #    - e002_hp_dn_basic_mean
    - e002_hp_basic_max
    - e002_hp_basic_min
    - e002_hp_basic_std
    - e002_hp_basic_mean
    - e003_hp_dn_3_phase_basic_corr_0
    - e003_hp_dn_3_phase_basic_corr_1
    - e003_hp_dn_3_phase_basic_corr_2
