# preprocess settings
preprocess:
    resampling: False
    resampling_type: under
    resampling_seed: 71

# training settings
train:
    fold_num: 5
    with_label: True

# lightGBM parameters
lgbm_params:
    boosting: gbdt
    verbose: -1
    random_state: 71
    objective: binary
    metric: auc
    learning_rate: 0.05
    num_leaves: 80
    max_depth: -1
    subsample: 0.8
    bagging_freq: 1
    colsample_bytree: 0.8
    feature_fraction: 0.8
    min_data_in_leaf: 60
    lambda_l1: 0.1
    #    min_split_gain: 
    #    min_child_weight: 
    #    max_bin: 

# features
features: 
    #    - phase
    - e001_base_max
    - e001_base_min
    - e001_base_std
    - e002_hp_dn_basic_max
    - e002_hp_dn_basic_min
    - e002_hp_dn_basic_std
      #    - e002_hp_dn_basic_mean
    - e002_hp_basic_max
    - e002_hp_basic_min
    - e002_hp_basic_std
    - e002_hp_basic_mean
    - e003_hp_dn_3_phase_basic_corr_0
    - e003_hp_dn_3_phase_basic_corr_1
    - e003_hp_dn_3_phase_basic_corr_2
    - e006_hp_dn_percentiles_perc1
    - e006_hp_dn_percentiles_perc5
    - e006_hp_dn_percentiles_perc10
    - e006_hp_dn_percentiles_perc90
    - e006_hp_dn_percentiles_perc95
    - e006_hp_dn_percentiles_perc99
    - e006_hp_dn_percentiles_perc99m1
    - e006_hp_dn_percentiles_perc95m5
    - e006_hp_dn_percentiles_perc90m10
    - e006_hp_dn_percentiles_perc1p99
    - e006_hp_dn_percentiles_perc5p95
    - e006_hp_dn_percentiles_perc10p90
    - e007_hp_dn_abs_thresh_overs_th1_count
    - e007_hp_dn_abs_thresh_overs_th1_time_std
    - e007_hp_dn_abs_thresh_overs_th1_time_skew
    - e007_hp_dn_abs_thresh_overs_th1_time_kurt
    - e007_hp_dn_abs_thresh_overs_th3_count
    - e007_hp_dn_abs_thresh_overs_th3_time_std
    - e007_hp_dn_abs_thresh_overs_th3_time_skew
    - e007_hp_dn_abs_thresh_overs_th3_time_kurt
    - e007_hp_dn_abs_thresh_overs_th5_count
    - e007_hp_dn_abs_thresh_overs_th5_time_std
    - e007_hp_dn_abs_thresh_overs_th5_time_skew
    - e007_hp_dn_abs_thresh_overs_th5_time_kurt
    - e007_hp_dn_abs_thresh_overs_th10_count
    - e007_hp_dn_abs_thresh_overs_th10_time_std
    - e007_hp_dn_abs_thresh_overs_th10_time_skew
    - e007_hp_dn_abs_thresh_overs_th10_time_kurt
      #    - e008_hp_dn_scaled_group_scaled_kurt
      #    - e008_hp_dn_scaled_group_scaled_mean
      #- e008_hp_dn_scaled_group_scaled_skew
      #    - e008_hp_dn_scaled_group_scaled_std
      #    - e008_hp_dn_scaled_phase_scaled_kurt
      #- e008_hp_dn_scaled_phase_scaled_mean
      #    - e008_hp_dn_scaled_phase_scaled_skew
      #    - e008_hp_dn_scaled_phase_scaled_std

